### ISSUE TITLE
SW 6.0.0.ea1.1: Column "auto_increment" got removed from products

### ISSUE THREAD

**Issue by mo-mueller** [DivanteLtd/shopware2vuestorefront#22]
When I start the product indexer I'm getting the following error:

```
TypeError: Cannot read property 'toString' of undefined
    at configurable (.../vsf-shopware-indexer/src/modules/product/template.js:34:28)
    at transformedProduct (.../vsf-shopware-indexer/src/modules/product/transformer.js:182:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Thats because the product attribute "auto_increment" does not exists anymore in SW 6.0.0.ea1.1

**Comment by mitelg** [comment]
FYI: this has been reverted in the meantime and will be part of the EA2 again:
https://github.com/shopware/platform/blob/master/src/Core/Content/Product/ProductDefinition.php#L117

**Comment by mo-mueller** [comment]
Ah ok. So I have to wait for EA2 to use vue storefront? Or will there be a temporary fix?

**Comment by mitelg** [comment]
If the awesome vueStorefront guys do not supply a workaround for that specific EA1.1 version, I simply would wait for the next EA version. 
You could of course use the dev  version of Shopware 6, to always have the latest changes
